# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Laurent Charignon
tagline:             'Blog'
description:         'Technical blog by Laurent Charignon'
url:                 http://charignon.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Laurent Charignon
  url:               https://www.facebook.com/laurent.charignon
  email:             laurent3814@hotmail.com

# Custom vars
version:             1.0.0
